---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  # POSIX cron format
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html
  schedule:
  # Once every 5 minutes
  # - cron: "*/5 * * * *"
  # Once a month
  - cron: "0 0 1 * *"
jobs:
  Test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "/home/runner/go"
    steps:
    - run: "echo \"/usr/local/go/bin\" >> \"$GITHUB_PATH\""
    - run: "echo \"${GOPATH}/bin\" >> \"$GITHUB_PATH\""
    - run: "echo \"${GITHUB_WORKSPACE}/bin\" >> \"$GITHUB_PATH\""
    - uses: "actions/checkout@v4"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y curl python3-venv"
    - run: "curl -LO https://go.dev/dl/go1.23.2.linux-amd64.tar.gz"
    - run: "sudo tar -C /usr/local -xzf go1.23.2.linux-amd64.tar.gz"
    - run: "./install"
    - run: "./build"
